[INFO -- 2018-10-19 06:02:48]
Starting flip_value script
version: 1.1
[INFO -- 2018-10-19 06:02:48]
Initialization strings:
[INFO -- 2018-10-19 06:02:48]
(1) file /home/latansini/Desktop/trabalhoftf/carol-fi/sample-code/knn/nn-knl-files/nn
[INFO -- 2018-10-19 06:02:48]
(2) set args /home/latansini/Desktop/trabalhoftf/carol-fi/sample-code/knn/nn-knl-files/filelist 15 25 25 /home/latansini/Desktop/trabalhoftf/carol-fi/sample-code/knn/nn-knl-files/out15_25_25
[INFO -- 2018-10-19 06:02:48]
initSignal:2
[INFO -- 2018-10-19 06:02:48]
endSignal:3
[INFO -- 2018-10-19 06:02:48]
faultModel:2
[EXCEPTION -- 2018-10-19 06:02:50]
gdbException: No symbol "None" in current context.
[EXCEPTION -- 2018-10-19 06:02:50]
pythonException: invalid frame
[EXCEPTION -- 2018-10-19 06:02:50]
pythonException: invalid frame
[EXCEPTION -- 2018-10-19 06:02:50]
pythonException: invalid frame
[EXCEPTION -- 2018-10-19 06:02:50]
pythonException: invalid frame
[INFO -- 2018-10-19 06:02:50]
Backtrace BEGIN:
#0  0x00007ffff78bddf3 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff78bb6da in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff768f184 in start_thread (arg=0x7ffff70b9700) at pthread_create.c:312
#3  0x00007ffff73bc03d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

425	in strtod_l.c

Backtrace END
Fliping a bit of the value pointed by a pointer
Memory content before bitflip:0x2f
Fault Model: Random bit-flip
base address to flip value: 0x7fffffffdd00 
address max offset: 1
Memory content after  bitflip:0xa3
frame name: main
symbol name: gold_filename
symbol filename: nn.c
symbol line: 35
value: 0x7fffffffdd00 "\243home/latansini/Desktop/trabalhoftf/carol-fi/sample-code/knn/nn-knl-files/out15_25_25"
value address: 0x7fffffffd550
Type: The type is a pointer.
Type sizeof: 8

[INFO -- 2018-10-19 06:02:50]
Fault Injection Successful after 2.064492702484131s
[INFO -- 2018-10-19 06:02:50]
event type: exit
[EXCEPTION -- 2018-10-19 06:02:50]
exit code: no exit code available
[EXCEPTION -- 2018-10-19 06:02:50]
pythonException: Thread no longer exists.
