[INFO -- 2018-10-19 04:32:52]
Starting flip_value script
version: 1.1
[INFO -- 2018-10-19 04:32:52]
Initialization strings:
[INFO -- 2018-10-19 04:32:52]
(1) file /home/latansini/Desktop/trabalhoftf/carol-fi/sample-code/knn/nn-knl-files/nn
[INFO -- 2018-10-19 04:32:52]
(2) set args /home/latansini/Desktop/trabalhoftf/carol-fi/sample-code/knn/nn-knl-files/filelist 15 25 25 /home/latansini/Desktop/trabalhoftf/carol-fi/sample-code/knn/nn-knl-files/out15_25_25
[INFO -- 2018-10-19 04:32:52]
initSignal:0
[INFO -- 2018-10-19 04:32:52]
endSignal:1
[INFO -- 2018-10-19 04:32:52]
faultModel:0
[EXCEPTION -- 2018-10-19 04:32:53]
pythonException: invalid frame
[INFO -- 2018-10-19 04:32:53]
Backtrace BEGIN:
#0  0x00007ffff78bdc2e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff78bb69b in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff768f184 in start_thread (arg=0x7ffff68b8700) at pthread_create.c:312
#3  0x00007ffff73bc03d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

30	    FILE   *flist,*fp;
31	    int    i=0,j=0, k=0, rec_count=0, done=0;
32	    char   sandbox[REC_LENGTH * REC_WINDOW], *rec_iter,*rec_iter2, dbname[64];
33	    struct neighbor *neighbors = NULL;
34	    float target_lat, target_long, tmp_lat=0, tmp_long=0;
35	    char * gold_filename;
36	    long rec_sum = 0;
37	
38	    if(argc < 6) {
39	        fprintf(stderr, "Invalid set of arguments:\n");

Backtrace END
Memory content before bitflip:0x0a0x000x000x000x000x000x000x00
Fault Model: Single bit-flip
base address to flip value: 0x7fffffffd530
address max offset: 8
Memory content after  bitflip:0x0a0x040x000x000x000x000x000x00
frame name: main
symbol name: rec_sum
symbol filename: nn.c
symbol line: 36
value: 1034
value address: 0x7fffffffd530
Type: The type is an integer type.
Type sizeof: 8

[INFO -- 2018-10-19 04:32:53]
Fault Injection Successful after 1.032397747039795s
[INFO -- 2018-10-19 04:32:53]
event type: exit
[EXCEPTION -- 2018-10-19 04:32:53]
exit code: no exit code available
[EXCEPTION -- 2018-10-19 04:32:53]
pythonException: Thread no longer exists.
