[INFO -- 2018-12-03 13:00:34]
Starting flip_value script
version: 1.1
[INFO -- 2018-12-03 13:00:34]
Initialization strings:
[INFO -- 2018-12-03 13:00:34]
(1) file /home/latansini/carol-fi/carol-fi/codes/nnfulldup/nn-knl-files/nn
[INFO -- 2018-12-03 13:00:34]
(2) set args /home/latansini/carol-fi/carol-fi/codes/nnfulldup/nn-knl-files/filelist 20 5 5 /home/latansini/carol-fi/carol-fi/codes/nnfulldup/nn-knl-files/out20_5_5
[INFO -- 2018-12-03 13:00:34]
initSignal:0
[INFO -- 2018-12-03 13:00:34]
endSignal:2
[INFO -- 2018-12-03 13:00:34]
faultModel:1
[EXCEPTION -- 2018-12-03 13:00:35]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 13:00:35]
pythonException: invalid frame
[INFO -- 2018-12-03 13:00:35]
Backtrace BEGIN:
#0  0x00007ffff78d4e49 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff78d2722 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff76b0064 in start_thread (arg=0x7ffff52f8700) at pthread_create.c:309
#3  0x00007ffff73e562d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

188	
189	    filename = argv[1];
190	    k = atoi(argv[2]);
191	    target_lat = atof(argv[3]);
192	    target_long = atof(argv[4]);
193	    gold_filename = argv[5];
194	
195	    data1 = nn_wrapper(filename, k, target_lat, target_long);
196	    data2 = nn_wrapper(filename, k, target_lat, target_long);
197	

Backtrace END
Memory content before bitflip:0x000x000x000x00
Fault Model: Double bit-flip
base address to flip value: 0x7fffffffe3fc
address max offset: 4
Memory content after  bitflip:0x000x000x000x05
frame name: nn_wrapper
symbol name: tmp_lat
symbol filename: nn.c
symbol line: 29
value: 6.01853108e-36
value address: 0x7fffffffe3fc
Type: A floating point type.
Type sizeof: 4

[INFO -- 2018-12-03 13:00:35]
Fault Injection Successful after 1.13595700264s
[INFO -- 2018-12-03 13:00:35]
event type: exit
[EXCEPTION -- 2018-12-03 13:00:35]
exit code: no exit code available
[EXCEPTION -- 2018-12-03 13:00:35]
pythonException: Thread no longer exists.
[EXCEPTION -- 2018-12-03 13:00:35]
pythonException: Thread no longer exists.
